### ISSUE TITLE
ID System

### ISSUE THREAD

**Issue by bosco4** [CMPUT301W21T23/CMPUT301W21T23-SmartDataBook#1]
Login menu to maintain unique users
1.) Login ID
2.) Create new Account (New ID)

**Comment by whqkdhfh13** [comment]
Account class
* Getter/Setter of attributes for editing the profile
* Type of accounts
* Ownership of experiments/trials

Storage class for storing and managing accounts
* Registration feature
* Validating identities feature
* Remove account features
