### ISSUE TITLE
See Experiment result page

### ISSUE THREAD

**Issue by Alex-Mak-MCW** [CMPUT301W21T23/CMPUT301W21T23-SmartDataBook#9]

**Comment by Alex-Mak-MCW** [comment]
A page that:

Sees the experiment's result (whether in statistics, graphs, plots, or QR code)

Sees the statistics ( median, mean, standard deviations) of the trials

Sees the experiment's information (owner's name, date of lab created)

**Comment by whqkdhfh13** [comment]
Duplicate of #6 , issue closed
